from detectron2.config.defaults import _C
from detectron2.config import CfgNode as CN

_CC = _C

# ----------- Backbone ----------- #
_CC.MODEL.BACKBONE.FREEZE = False
_CC.MODEL.BACKBONE.FREEZE_AT = 3

# ------------- RPN -------------- #
_CC.MODEL.RPN.FREEZE = False
_CC.MODEL.RPN.ENABLE_DECOUPLE = False
_CC.MODEL.RPN.BACKWARD_SCALE = 1.0

# ------------- ROI -------------- #
_CC.MODEL.ROI_HEADS.NAME = "Res5ROIHeads"
_CC.MODEL.ROI_HEADS.FREEZE_FEAT = False
_CC.MODEL.ROI_HEADS.ENABLE_DECOUPLE = False
_CC.MODEL.ROI_HEADS.BACKWARD_SCALE = 1.0
_CC.MODEL.ROI_HEADS.OUTPUT_LAYER = "FastRCNNOutputLayers"
_CC.MODEL.ROI_HEADS.CLS_DROPOUT = False
_CC.MODEL.ROI_HEADS.DROPOUT_RATIO = 0.8
_CC.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 7  # for faster

# ------------- TEST ------------- #
_CC.TEST.PCB_ENABLE = False
_CC.TEST.PCB_MODELTYPE = 'resnet'             # res-like
_CC.TEST.PCB_MODELPATH = ""
_CC.TEST.PCB_ALPHA = 0.50
_CC.TEST.PCB_UPPER = 1.0
_CC.TEST.PCB_LOWER = 0.05
_CC.TEST.EVAL_START = 0

# ------------ Other ------------- #
_CC.SOLVER.WEIGHT_DECAY = 5e-5
_CC.MUTE_HEADER = True

# ------------ MFDC ------------- #
_CC.DATASETS.TWO_STREAM = False
_CC.MODEL.ROI_HEADS.MEMORY = False
_CC.MODEL.ROI_HEADS.AUGMENTATION = False
_CC.MODEL.ROI_HEADS.SEMANTIC = False
_CC.MODEL.ROI_HEADS.WARMUP_DISTILL = 200
_CC.MODEL.ROI_HEADS.QUEUE_LEN = 2048


# add
_CC.MODEL.EVAL_USE_GT_BOXES = False
# ------------ Attribute Modules ------------- #
_CC.MODEL.ATTRIBUTE = CN()
_CC.MODEL.ATTRIBUTE.ENABLED = False
_CC.MODEL.ATTRIBUTE.CLASS_NAMES = []
_CC.MODEL.ATTRIBUTE.BACKGROUND_CLASS = "background"
_CC.MODEL.ATTRIBUTE.SUPER_ATTR_PATH = ""
_CC.MODEL.ATTRIBUTE.EMBEDDING_DIM = 512
_CC.MODEL.ATTRIBUTE.HIDDEN_DIM = 512
_CC.MODEL.ATTRIBUTE.LOSS_WEIGHT = 1.0
_CC.MODEL.ATTRIBUTE.CONTRASTIVE_WEIGHT = 0.1
_CC.MODEL.ATTRIBUTE.TEMPERATURE = 0.07
_CC.MODEL.ATTRIBUTE.CLUSTER_LOSS_WEIGHT = 1.0
_CC.MODEL.ATTRIBUTE.BG_THRESHOLD = 0.5
_CC.MODEL.ATTRIBUTE.PSEUDO_THRESHOLD = 0.7
_CC.MODEL.ATTRIBUTE.BG_SUPPRESSION_WEIGHT = 0.0
_CC.MODEL.ATTRIBUTE.INFERENCE_ALPHA = 0.0
_CC.MODEL.ATTRIBUTE.EVAL_THRESHOLD = 0.5
_CC.MODEL.ATTRIBUTE.EVAL_MATCH_IOU = 0.5
_CC.MODEL.ATTRIBUTE.EVAL_RESULTS_PATH = "eval_results.pt"
_CC.MODEL.ATTRIBUTE.BACKWARD_SCALE = 0.01

# ------------ Attribute Graph Reasoning -------------
# 默认使用 HGNN；下面三个开关用于消融实验，建议与 HGNN.ENABLED 互斥：
#   woHGNN: 不做任何图传播，直接使用原始 cluster embeddings
#   USE_GNN: 用简单图卷积（仅 similarity 图）替代 HGNN
#   Incidence_ONLY: 仅基于 incidence 做无参数传播，不使用 similarity
_CC.MODEL.ATTRIBUTE.woHGNN = False
_CC.MODEL.ATTRIBUTE.USE_GNN = False
_CC.MODEL.ATTRIBUTE.Incidence_ONLY = False
_CC.MODEL.ATTRIBUTE.HGNN = CN()
_CC.MODEL.ATTRIBUTE.HGNN.ENABLED = False
_CC.MODEL.ATTRIBUTE.HGNN.HIDDEN_DIM = 512
_CC.MODEL.ATTRIBUTE.HGNN.NUM_LAYERS = 2
_CC.MODEL.ATTRIBUTE.HGNN.SIMILARITY_WEIGHT = 0.2

# ------------ Attribute Bilinear Matcher -------------
_CC.MODEL.ATTRIBUTE.BILINEAR = CN()
_CC.MODEL.ATTRIBUTE.BILINEAR.ENABLED = False
_CC.MODEL.ATTRIBUTE.BILINEAR.PROJ_DIM = 0
_CC.MODEL.ATTRIBUTE.BILINEAR.NORMALIZE = True

# ------------ Attribute Cluster Projector -------------
_CC.MODEL.ATTRIBUTE.CLUSTER_PROJECTOR = CN()
_CC.MODEL.ATTRIBUTE.CLUSTER_PROJECTOR.ENABLED = False
_CC.MODEL.ATTRIBUTE.CLUSTER_PROJECTOR.HIDDEN_DIM = 0
_CC.MODEL.ATTRIBUTE.CLUSTER_PROJECTOR.NORMALIZE = True

# ------------ Attribute Monitor (TensorBoard) -------------
_CC.MODEL.ATTRIBUTE.MONITOR = CN()
_CC.MODEL.ATTRIBUTE.MONITOR.ENABLED = True
_CC.MODEL.ATTRIBUTE.MONITOR.LOG_PERIOD = 25
_CC.MODEL.ATTRIBUTE.MONITOR.LOG_DIR = "tb_attr"
_CC.MODEL.ATTRIBUTE.MONITOR.MAX_GATE_LOG = 25
_CC.MODEL.ATTRIBUTE.MONITOR.LOG_IMAGES = True
_CC.MODEL.ATTRIBUTE.MONITOR.LOG_HIST = True

# ------------ Background Filter Monitor (TensorBoard) -------------
_CC.MODEL.ATTRIBUTE.BG_FILTER_MONITOR = CN()
_CC.MODEL.ATTRIBUTE.BG_FILTER_MONITOR.ENABLED = False
_CC.MODEL.ATTRIBUTE.BG_FILTER_MONITOR.LOG_PERIOD = 25
_CC.MODEL.ATTRIBUTE.BG_FILTER_MONITOR.LOG_DIR = "tb_bg_filter"
_CC.MODEL.ATTRIBUTE.BG_FILTER_MONITOR.MAX_IMAGES = 4
_CC.MODEL.ATTRIBUTE.BG_FILTER_MONITOR.MAX_ROIS = 400
_CC.MODEL.ATTRIBUTE.BG_FILTER_MONITOR.MIN_ACTION_TYPES = 2
_CC.MODEL.ATTRIBUTE.BG_FILTER_MONITOR.CHECK_EVERY_ITER = True


# ------------ Attribute Optimizer --暂时未启用，预留接口：build_attribute_optimizer
_CC.MODEL.ATTRIBUTE.WARMUP_ITERS = _CC.MODEL.ROI_HEADS.WARMUP_DISTILL # 属性模块开始训练的 WARMUP_ITERS
_CC.SOLVER.ATTRIBUTE = CN()
_CC.SOLVER.ATTRIBUTE.BASE_LR = 0.0 # 此时使用 SOLVER.BASE_LR
_CC.SOLVER.ATTRIBUTE.LR_SCHEDULER_NAME = "WarmupMultiStepLR"
_CC.SOLVER.ATTRIBUTE.STEPS = (60000, 80000)
_CC.SOLVER.ATTRIBUTE.GAMMA = 0.1
_CC.SOLVER.ATTRIBUTE.WARMUP_FACTOR = 0.001
_CC.SOLVER.ATTRIBUTE.WARMUP_ITERS = 0 # 学习率 WARMUP_FACTOR 从 0.001 到 1 的 WARMUP_ITERS
_CC.SOLVER.ATTRIBUTE.WARMUP_METHOD = "linear"
_CC.SOLVER.ATTRIBUTE.MOMENTUM = 0.9
_CC.SOLVER.ATTRIBUTE.WEIGHT_DECAY = 5.0e-05
_CC.SOLVER.ATTRIBUTE.NESTEROV = False

_CC.MODEL.ATTRIBUTE.FREEZE_ALIGN_BILINEAR = False
_CC.MODEL.ATTRIBUTE.FREEZE_ALIGN_CLUSTER_PROJECTOR = False
_CC.MODEL.ATTRIBUTE.ATTR_GLOBAL_BG_FILTER = False

_CC.MODEL.ATTRIBUTE.WITH_CENTER_NORM = False
_CC.MODEL.ATTRIBUTE.POOLED = True

_CC.SOLVER.ATTRIBUTE.LR_MULT = 1.0
_CC.MODEL.ATTRIBUTE.MARGIN_THRE = 0.1
